### ISSUE TITLE
Any Support for Guzzle 6 Moving Forward

### ISSUE THREAD

**Issue by lindleywhite** [packaged/api#2]
This library is being used by a dependency of mine and I have other dependencies that are relying on Guzzle 6. Would it be hard to implement it within this package?

**Comment by bajb** [comment]
Hey, 

Which package depends on packaged/api so I can take a look at its requirements.

Thanks

**Comment by lindleywhite** [comment]
Looks like Fortifi API is the one that depends on packaged/api

``` json
{
  "name": "fortifi/fortifi-api",
  "description": "Fortifi Business Platform API",
  "homepage": "http://fortifi.co",
  "license": "BSD-3-Clause",
  "require": {
    "packaged/api": "~0.4",
    "packaged/helpers": "~1.0"
  },
  "require-dev": {
    "phpunit/phpunit": "~4.6"
  },
  "autoload": {
    "psr-4": {
      "Fortifi\\FortifiApi\\": "src/"
    }
  }
}
```

**Comment by TomK** [comment]
closing as Guzzle 6 is supported in the latest release 98f65f50a69fca3a816fefd293f236acdd205769
